#!/usr/bin/env python3
"""Generate tang/src/bk/az_palette.v: the AZBK's palette RAM with its
power-up contents.

The 338 entries are GID's (BKemu v4.6, devemu/AZBK.cpp, m_azPalette),
which are the AZBK firmware v15's: 0-255 the 256-colour palette (32
greys, 8 primaries, then the web-safe 216), 256-319 the sixteen legacy
4-colour palettes, 320-335 the 16-colour one, 336-337 monochrome.  Each
24-bit colour becomes 15 bits, five a channel (R5G5B5, red on top), as
the controller's 177236 register holds it.  The start ROM reloads the
palette at every start, so this is the picture before it runs and the
fall-back should a tool not initialise the RAM.
"""
import sys, re, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT  = os.path.join(ROOT, "tang", "src", "bk", "az_palette.v")

GREYS = [0x000000,0x0f0f0f,0x101010,0x1f1f1f,0x202020,0x2f2f2f,0x303030,0x3f3f3f,
         0x404040,0x4f4f4f,0x505050,0x5f5f5f,0x606060,0x6f6f6f,0x707070,0x7f7f7f,
         0x808080,0x8f8f8f,0x909090,0x9f9f9f,0xa0a0a0,0xafafaf,0xb0b0b0,0xbfbfbf,
         0xc0c0c0,0xcfcfcf,0xd0d0d0,0xdfdfdf,0xe0e0e0,0xefefef,0xf0f0f0,0xffffff]
PRIM  = [0x000000,0x0000ff,0x00ff00,0x00ffff,0xff0000,0xff00ff,0xffff00,0xffffff]
WEB   = [(r << 16) | (g << 8) | b for r in (0,0x33,0x66,0x99,0xcc,0xff)
         for g in (0,0x33,0x66,0x99,0xcc,0xff) for b in (0,0x33,0x66,0x99,0xcc,0xff)]
PAL4 = [0x000000,0x0000ff,0x00ff00,0xff0000, 0x000000,0xffff00,0xff00ff,0xff0000,
        0x000000,0x00ffff,0x0000ff,0xff00ff, 0x000000,0x00ff00,0x00ffff,0xffff00,
        0x000000,0xff00ff,0x00ffff,0xffffff, 0x000000,0xffffff,0xffffff,0xffffff,
        0x000000,0xbf0000,0x9f0000,0xff0000, 0x000000,0xbfff00,0x9fff00,0xffff00,
        0x000000,0xbf00ff,0x9f00ff,0xff00ff, 0x000000,0x9fff00,0x9f00ff,0x9f0000,
        0x000000,0xb8ff00,0xbf00ff,0xbf0000, 0x000000,0x00ffff,0xffff00,0xff0000,
        0x000000,0xff0000,0x00ff00,0x00ffff, 0x000000,0x00ffff,0xffff00,0xffffff,
        0x000000,0xffff00,0x00ff00,0xffffff, 0x000000,0x00ffff,0x00ff00,0xffffff]
PAL16 = [0x000000,0x0000aa,0x00aa00,0x00aaaa,0xaa0000,0xaa00aa,0xaa5500,0xaaaaaa,
         0x555555,0x0000ff,0x00ff00,0x00ffff,0xff0000,0xff00ff,0xffff00,0xffffff]
PAL2 = [0x000080, 0xffffff]

pal = GREYS + PRIM + WEB + PAL4 + PAL16 + PAL2
assert len(pal) == 338, len(pal)

def r5g5b5(c):
    r, g, b = (c >> 16) & 0xff, (c >> 8) & 0xff, c & 0xff
    return ((r >> 3) << 10) | ((g >> 3) << 5) | (b >> 3)

lines = []
lines.append("`timescale 1ns / 1ps")
lines.append("//========================================================================")
lines.append("// az_palette.v - the AZBK's palette: 512 x 15 bits, two ports, with the")
lines.append("// firmware's default contents.  GENERATED by tools/palette.py - do not")
lines.append("// edit; the script's docstring says where the numbers come from.")
lines.append("//")
lines.append("// Port A is the processor's (177234/177236): a write, and a read that")
lines.append("// follows the cell register.  Port B is the pixel pipeline's.")
lines.append("//========================================================================")
lines.append("module az_palette (")
lines.append("    input             clk,")
lines.append("    input      [8:0]  a_adr,")
lines.append("    input             a_we,")
lines.append("    input      [14:0] a_din,")
lines.append("    output reg [14:0] a_dout,")
lines.append("    input      [8:0]  b_adr,")
lines.append("    output reg [14:0] b_dout,")
lines.append("    input             reload      // one clock: cells 256-337 back to the table (82 clocks)")
lines.append(");")
lines.append("")
lines.append("reg [14:0] mem [0:511];")
lines.append("")
lines.append("integer i;")
lines.append("initial begin")
lines.append("    for (i = 0; i < 512; i = i + 1) mem[i] = 15'd0;")
for i, c in enumerate(pal):
    lines.append("    mem[%3d] = 15'h%04x;   // %06x" % (i, r5g5b5(c), c))
lines.append("end")
lines.append("")
lines.append("// the reload (the controller's hotkey АР2+РУС, azvideo.v): one cell a")
lines.append("// clock through port A, ahead of the processor's write for those clocks")
lines.append("reg [8:0] rl_adr = 9'd0;")
lines.append("reg       rl_on  = 1'b0;")
lines.append("always @(posedge clk) begin")
lines.append("    if (reload) begin rl_on <= 1'b1; rl_adr <= 9'd256; end")
lines.append("    else if (rl_on) begin rl_adr <= rl_adr + 9'd1; if (rl_adr == 9'd337) rl_on <= 1'b0; end")
lines.append("end")
lines.append("")
lines.append("always @(posedge clk) begin")
lines.append("    if (rl_on)     mem[rl_adr] <= def_pal(rl_adr);")
lines.append("    else if (a_we) mem[a_adr] <= a_din;")
lines.append("    else           a_dout <= mem[a_adr];")
lines.append("end")
lines.append("")
lines.append("always @(posedge clk) b_dout <= mem[b_adr];")
lines.append("")
lines.append("// the same table as a function, for azvideo.v's palette reset (the")
lines.append("// controller's hotkey АР2+РУС): cells 256-337, the legacy sets, the")
lines.append("// 16-colour set and the monochrome pair, back to their power-up values")
lines.append("function [14:0] def_pal;")
lines.append("    input [8:0] i;")
lines.append("    case (i)")
for i, c in enumerate(pal):
    if i >= 256:
        lines.append("        9'd%3d: def_pal = 15'h%04x;" % (i, r5g5b5(c)))
lines.append("        default: def_pal = 15'd0;")
lines.append("    endcase")
lines.append("endfunction")
lines.append("")
lines.append("endmodule")
open(OUT, "w").write("\n".join(lines) + "\n")
print("wrote", OUT, "with", len(pal), "colours")
