#!/usr/bin/env python3
"""tonegen.py - the sample tables soft/src/dmatest.mac plays.

    tonegen.py OUT.mac

Three tables, 2048 bytes each, that loop seamlessly at 44100 Hz:
  PCMDAT  1024 words of 16-bit signed PCM, a sine of 10 cycles (430.7 Hz)
  IMAMON  4096 IMA ADPCM nibbles, mono, a sine of 40 cycles (430.7 Hz),
          low nibble first, at 12000 (the coder starts from index 0 at
          every loop and needs a few dozen samples to catch a loud sine)
  IMAST   2048 IMA ADPCM frames, stereo, a byte a frame, left in the low
          nibble (20 cycles, 430.7 Hz), right in the high (30, 646 Hz)
The encoder is the standard IMA one, started from predictor 0 and index
0, which is the state azsound.v's decoder (GID's ima.cpp) begins a
playback with and returns to at each loop unless bit 4 of 177160 keeps
it; the decoder below mirrors azsound.v step for step and the tables
are checked through it before they are written.
"""

import math
import sys

STEPS = [7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 19, 21, 23, 25, 28, 31, 34, 37, 41,
         45, 50, 55, 60, 66, 73, 80, 88, 97, 107, 118, 130, 143, 157, 173, 190,
         209, 230, 253, 279, 307, 337, 371, 408, 449, 494, 544, 598, 658, 724,
         796, 876, 963, 1060, 1166, 1282, 1411, 1552, 1707, 1878, 2066, 2272,
         2499, 2749, 3024, 3327, 3660, 4026, 4428, 4871, 5358, 5894, 6484, 7132,
         7845, 8630, 9493, 10442, 11487, 12635, 13899, 15289, 16818, 18500,
         20350, 22385, 24623, 27086, 29794, 32767]
INDEX = [-1, -1, -1, -1, 2, 4, 6, 8]


def clamp(v):
    return max(-32768, min(32767, v))


def decode_nibble(state, nib):
    """azsound.v: ima_diff, ima_next, ima_sum."""
    cur, idx = state
    step = STEPS[idx]
    diff = step >> 3
    if nib & 1:
        diff += step >> 2
    if nib & 2:
        diff += step >> 1
    if nib & 4:
        diff += step
    cur = clamp(cur - diff if nib & 8 else cur + diff)
    idx = max(0, min(88, idx + INDEX[nib & 7]))
    return (cur, idx), cur


def encode(samples):
    cur, idx = 0, 0
    out = []
    for s in samples:
        step = STEPS[idx]
        delta = s - cur
        nib = 0
        if delta < 0:
            nib = 8
            delta = -delta
        diff = step >> 3
        if delta >= step:
            nib |= 4
            delta -= step
            diff += step
        if delta >= step >> 1:
            nib |= 2
            delta -= step >> 1
            diff += step >> 1
        if delta >= step >> 2:
            nib |= 1
            diff += step >> 2
        cur = clamp(cur - diff if nib & 8 else cur + diff)
        idx = max(0, min(88, idx + INDEX[nib & 7]))
        out.append(nib)
    return out


def sine(n, cycles, amp=20000):
    return [int(round(amp * math.sin(2 * math.pi * cycles * i / n))) for i in range(n)]


def check(name, nibbles, wanted):
    # from index 0 the coder needs a few dozen samples to catch a loud
    # sine (the step doubles every four), so the loop point carries a
    # click; the error after that is what says the two agree
    state, err, start = (0, 0), 0, 0
    for i, (nib, w) in enumerate(zip(nibbles, wanted)):
        state, v = decode_nibble(state, nib)
        if i < 64:
            start = max(start, abs(v - w))
        else:
            err = max(err, abs(v - w))
    print(f"{name}: {len(nibbles)} samples, start-up error {start}, then {err}", file=sys.stderr)
    if err > 1500:
        raise SystemExit(f"{name}: the encoder and the decoder disagree")


def emit(f, label, data):
    f.write(f"{label}:\n")
    for i in range(0, len(data), 16):
        f.write("\t.BYTE\t" + ",".join(f"{b:o}" for b in data[i:i + 16]) + "\n")


def main():
    out = sys.argv[1]
    pcm = sine(1024, 10)
    pcm_bytes = []
    for s in pcm:
        pcm_bytes += [s & 0xFF, (s >> 8) & 0xFF]
    mono = encode(sine(4096, 40, 12000))
    check("IMA mono", mono, sine(4096, 40, 12000))
    mono_bytes = [mono[i] | mono[i + 1] << 4 for i in range(0, 4096, 2)]
    left, right = encode(sine(2048, 20, 12000)), encode(sine(2048, 30, 12000))
    check("IMA stereo left", left, sine(2048, 20, 12000))
    check("IMA stereo right", right, sine(2048, 30, 12000))
    st_bytes = [left[i] | right[i] << 4 for i in range(2048)]
    with open(out, "w") as f:
        f.write("; generated by tools/tonegen.py - the tables dmatest.mac plays\n")
        f.write("; PCMDAT 1024 words PCM16, IMAMON 4096 IMA mono nibbles, IMAST 2048 IMA stereo frames\n")
        emit(f, "PCMDAT", pcm_bytes)
        emit(f, "IMAMON", mono_bytes)
        emit(f, "IMAST", st_bytes)


if __name__ == "__main__":
    main()
