`timescale 1ns / 1ps
//========================================================================
// az_palette.v - the AZBK's palette: 512 x 15 bits, two ports, with the
// firmware's default contents.  GENERATED by tools/palette.py - do not
// edit; the script's docstring says where the numbers come from.
//
// Port A is the processor's (177234/177236): a write, and a read that
// follows the cell register.  Port B is the pixel pipeline's.
//========================================================================
module az_palette (
    input             clk,
    input      [8:0]  a_adr,
    input             a_we,
    input      [14:0] a_din,
    output reg [14:0] a_dout,
    input      [8:0]  b_adr,
    output reg [14:0] b_dout,
    input             reload      // one clock: cells 256-337 back to the table (82 clocks)
);

reg [14:0] mem [0:511];

integer i;
initial begin
    for (i = 0; i < 512; i = i + 1) mem[i] = 15'd0;
    mem[  0] = 15'h0000;   // 000000
    mem[  1] = 15'h0421;   // 0f0f0f
    mem[  2] = 15'h0842;   // 101010
    mem[  3] = 15'h0c63;   // 1f1f1f
    mem[  4] = 15'h1084;   // 202020
    mem[  5] = 15'h14a5;   // 2f2f2f
    mem[  6] = 15'h18c6;   // 303030
    mem[  7] = 15'h1ce7;   // 3f3f3f
    mem[  8] = 15'h2108;   // 404040
    mem[  9] = 15'h2529;   // 4f4f4f
    mem[ 10] = 15'h294a;   // 505050
    mem[ 11] = 15'h2d6b;   // 5f5f5f
    mem[ 12] = 15'h318c;   // 606060
    mem[ 13] = 15'h35ad;   // 6f6f6f
    mem[ 14] = 15'h39ce;   // 707070
    mem[ 15] = 15'h3def;   // 7f7f7f
    mem[ 16] = 15'h4210;   // 808080
    mem[ 17] = 15'h4631;   // 8f8f8f
    mem[ 18] = 15'h4a52;   // 909090
    mem[ 19] = 15'h4e73;   // 9f9f9f
    mem[ 20] = 15'h5294;   // a0a0a0
    mem[ 21] = 15'h56b5;   // afafaf
    mem[ 22] = 15'h5ad6;   // b0b0b0
    mem[ 23] = 15'h5ef7;   // bfbfbf
    mem[ 24] = 15'h6318;   // c0c0c0
    mem[ 25] = 15'h6739;   // cfcfcf
    mem[ 26] = 15'h6b5a;   // d0d0d0
    mem[ 27] = 15'h6f7b;   // dfdfdf
    mem[ 28] = 15'h739c;   // e0e0e0
    mem[ 29] = 15'h77bd;   // efefef
    mem[ 30] = 15'h7bde;   // f0f0f0
    mem[ 31] = 15'h7fff;   // ffffff
    mem[ 32] = 15'h0000;   // 000000
    mem[ 33] = 15'h001f;   // 0000ff
    mem[ 34] = 15'h03e0;   // 00ff00
    mem[ 35] = 15'h03ff;   // 00ffff
    mem[ 36] = 15'h7c00;   // ff0000
    mem[ 37] = 15'h7c1f;   // ff00ff
    mem[ 38] = 15'h7fe0;   // ffff00
    mem[ 39] = 15'h7fff;   // ffffff
    mem[ 40] = 15'h0000;   // 000000
    mem[ 41] = 15'h0006;   // 000033
    mem[ 42] = 15'h000c;   // 000066
    mem[ 43] = 15'h0013;   // 000099
    mem[ 44] = 15'h0019;   // 0000cc
    mem[ 45] = 15'h001f;   // 0000ff
    mem[ 46] = 15'h00c0;   // 003300
    mem[ 47] = 15'h00c6;   // 003333
    mem[ 48] = 15'h00cc;   // 003366
    mem[ 49] = 15'h00d3;   // 003399
    mem[ 50] = 15'h00d9;   // 0033cc
    mem[ 51] = 15'h00df;   // 0033ff
    mem[ 52] = 15'h0180;   // 006600
    mem[ 53] = 15'h0186;   // 006633
    mem[ 54] = 15'h018c;   // 006666
    mem[ 55] = 15'h0193;   // 006699
    mem[ 56] = 15'h0199;   // 0066cc
    mem[ 57] = 15'h019f;   // 0066ff
    mem[ 58] = 15'h0260;   // 009900
    mem[ 59] = 15'h0266;   // 009933
    mem[ 60] = 15'h026c;   // 009966
    mem[ 61] = 15'h0273;   // 009999
    mem[ 62] = 15'h0279;   // 0099cc
    mem[ 63] = 15'h027f;   // 0099ff
    mem[ 64] = 15'h0320;   // 00cc00
    mem[ 65] = 15'h0326;   // 00cc33
    mem[ 66] = 15'h032c;   // 00cc66
    mem[ 67] = 15'h0333;   // 00cc99
    mem[ 68] = 15'h0339;   // 00cccc
    mem[ 69] = 15'h033f;   // 00ccff
    mem[ 70] = 15'h03e0;   // 00ff00
    mem[ 71] = 15'h03e6;   // 00ff33
    mem[ 72] = 15'h03ec;   // 00ff66
    mem[ 73] = 15'h03f3;   // 00ff99
    mem[ 74] = 15'h03f9;   // 00ffcc
    mem[ 75] = 15'h03ff;   // 00ffff
    mem[ 76] = 15'h1800;   // 330000
    mem[ 77] = 15'h1806;   // 330033
    mem[ 78] = 15'h180c;   // 330066
    mem[ 79] = 15'h1813;   // 330099
    mem[ 80] = 15'h1819;   // 3300cc
    mem[ 81] = 15'h181f;   // 3300ff
    mem[ 82] = 15'h18c0;   // 333300
    mem[ 83] = 15'h18c6;   // 333333
    mem[ 84] = 15'h18cc;   // 333366
    mem[ 85] = 15'h18d3;   // 333399
    mem[ 86] = 15'h18d9;   // 3333cc
    mem[ 87] = 15'h18df;   // 3333ff
    mem[ 88] = 15'h1980;   // 336600
    mem[ 89] = 15'h1986;   // 336633
    mem[ 90] = 15'h198c;   // 336666
    mem[ 91] = 15'h1993;   // 336699
    mem[ 92] = 15'h1999;   // 3366cc
    mem[ 93] = 15'h199f;   // 3366ff
    mem[ 94] = 15'h1a60;   // 339900
    mem[ 95] = 15'h1a66;   // 339933
    mem[ 96] = 15'h1a6c;   // 339966
    mem[ 97] = 15'h1a73;   // 339999
    mem[ 98] = 15'h1a79;   // 3399cc
    mem[ 99] = 15'h1a7f;   // 3399ff
    mem[100] = 15'h1b20;   // 33cc00
    mem[101] = 15'h1b26;   // 33cc33
    mem[102] = 15'h1b2c;   // 33cc66
    mem[103] = 15'h1b33;   // 33cc99
    mem[104] = 15'h1b39;   // 33cccc
    mem[105] = 15'h1b3f;   // 33ccff
    mem[106] = 15'h1be0;   // 33ff00
    mem[107] = 15'h1be6;   // 33ff33
    mem[108] = 15'h1bec;   // 33ff66
    mem[109] = 15'h1bf3;   // 33ff99
    mem[110] = 15'h1bf9;   // 33ffcc
    mem[111] = 15'h1bff;   // 33ffff
    mem[112] = 15'h3000;   // 660000
    mem[113] = 15'h3006;   // 660033
    mem[114] = 15'h300c;   // 660066
    mem[115] = 15'h3013;   // 660099
    mem[116] = 15'h3019;   // 6600cc
    mem[117] = 15'h301f;   // 6600ff
    mem[118] = 15'h30c0;   // 663300
    mem[119] = 15'h30c6;   // 663333
    mem[120] = 15'h30cc;   // 663366
    mem[121] = 15'h30d3;   // 663399
    mem[122] = 15'h30d9;   // 6633cc
    mem[123] = 15'h30df;   // 6633ff
    mem[124] = 15'h3180;   // 666600
    mem[125] = 15'h3186;   // 666633
    mem[126] = 15'h318c;   // 666666
    mem[127] = 15'h3193;   // 666699
    mem[128] = 15'h3199;   // 6666cc
    mem[129] = 15'h319f;   // 6666ff
    mem[130] = 15'h3260;   // 669900
    mem[131] = 15'h3266;   // 669933
    mem[132] = 15'h326c;   // 669966
    mem[133] = 15'h3273;   // 669999
    mem[134] = 15'h3279;   // 6699cc
    mem[135] = 15'h327f;   // 6699ff
    mem[136] = 15'h3320;   // 66cc00
    mem[137] = 15'h3326;   // 66cc33
    mem[138] = 15'h332c;   // 66cc66
    mem[139] = 15'h3333;   // 66cc99
    mem[140] = 15'h3339;   // 66cccc
    mem[141] = 15'h333f;   // 66ccff
    mem[142] = 15'h33e0;   // 66ff00
    mem[143] = 15'h33e6;   // 66ff33
    mem[144] = 15'h33ec;   // 66ff66
    mem[145] = 15'h33f3;   // 66ff99
    mem[146] = 15'h33f9;   // 66ffcc
    mem[147] = 15'h33ff;   // 66ffff
    mem[148] = 15'h4c00;   // 990000
    mem[149] = 15'h4c06;   // 990033
    mem[150] = 15'h4c0c;   // 990066
    mem[151] = 15'h4c13;   // 990099
    mem[152] = 15'h4c19;   // 9900cc
    mem[153] = 15'h4c1f;   // 9900ff
    mem[154] = 15'h4cc0;   // 993300
    mem[155] = 15'h4cc6;   // 993333
    mem[156] = 15'h4ccc;   // 993366
    mem[157] = 15'h4cd3;   // 993399
    mem[158] = 15'h4cd9;   // 9933cc
    mem[159] = 15'h4cdf;   // 9933ff
    mem[160] = 15'h4d80;   // 996600
    mem[161] = 15'h4d86;   // 996633
    mem[162] = 15'h4d8c;   // 996666
    mem[163] = 15'h4d93;   // 996699
    mem[164] = 15'h4d99;   // 9966cc
    mem[165] = 15'h4d9f;   // 9966ff
    mem[166] = 15'h4e60;   // 999900
    mem[167] = 15'h4e66;   // 999933
    mem[168] = 15'h4e6c;   // 999966
    mem[169] = 15'h4e73;   // 999999
    mem[170] = 15'h4e79;   // 9999cc
    mem[171] = 15'h4e7f;   // 9999ff
    mem[172] = 15'h4f20;   // 99cc00
    mem[173] = 15'h4f26;   // 99cc33
    mem[174] = 15'h4f2c;   // 99cc66
    mem[175] = 15'h4f33;   // 99cc99
    mem[176] = 15'h4f39;   // 99cccc
    mem[177] = 15'h4f3f;   // 99ccff
    mem[178] = 15'h4fe0;   // 99ff00
    mem[179] = 15'h4fe6;   // 99ff33
    mem[180] = 15'h4fec;   // 99ff66
    mem[181] = 15'h4ff3;   // 99ff99
    mem[182] = 15'h4ff9;   // 99ffcc
    mem[183] = 15'h4fff;   // 99ffff
    mem[184] = 15'h6400;   // cc0000
    mem[185] = 15'h6406;   // cc0033
    mem[186] = 15'h640c;   // cc0066
    mem[187] = 15'h6413;   // cc0099
    mem[188] = 15'h6419;   // cc00cc
    mem[189] = 15'h641f;   // cc00ff
    mem[190] = 15'h64c0;   // cc3300
    mem[191] = 15'h64c6;   // cc3333
    mem[192] = 15'h64cc;   // cc3366
    mem[193] = 15'h64d3;   // cc3399
    mem[194] = 15'h64d9;   // cc33cc
    mem[195] = 15'h64df;   // cc33ff
    mem[196] = 15'h6580;   // cc6600
    mem[197] = 15'h6586;   // cc6633
    mem[198] = 15'h658c;   // cc6666
    mem[199] = 15'h6593;   // cc6699
    mem[200] = 15'h6599;   // cc66cc
    mem[201] = 15'h659f;   // cc66ff
    mem[202] = 15'h6660;   // cc9900
    mem[203] = 15'h6666;   // cc9933
    mem[204] = 15'h666c;   // cc9966
    mem[205] = 15'h6673;   // cc9999
    mem[206] = 15'h6679;   // cc99cc
    mem[207] = 15'h667f;   // cc99ff
    mem[208] = 15'h6720;   // cccc00
    mem[209] = 15'h6726;   // cccc33
    mem[210] = 15'h672c;   // cccc66
    mem[211] = 15'h6733;   // cccc99
    mem[212] = 15'h6739;   // cccccc
    mem[213] = 15'h673f;   // ccccff
    mem[214] = 15'h67e0;   // ccff00
    mem[215] = 15'h67e6;   // ccff33
    mem[216] = 15'h67ec;   // ccff66
    mem[217] = 15'h67f3;   // ccff99
    mem[218] = 15'h67f9;   // ccffcc
    mem[219] = 15'h67ff;   // ccffff
    mem[220] = 15'h7c00;   // ff0000
    mem[221] = 15'h7c06;   // ff0033
    mem[222] = 15'h7c0c;   // ff0066
    mem[223] = 15'h7c13;   // ff0099
    mem[224] = 15'h7c19;   // ff00cc
    mem[225] = 15'h7c1f;   // ff00ff
    mem[226] = 15'h7cc0;   // ff3300
    mem[227] = 15'h7cc6;   // ff3333
    mem[228] = 15'h7ccc;   // ff3366
    mem[229] = 15'h7cd3;   // ff3399
    mem[230] = 15'h7cd9;   // ff33cc
    mem[231] = 15'h7cdf;   // ff33ff
    mem[232] = 15'h7d80;   // ff6600
    mem[233] = 15'h7d86;   // ff6633
    mem[234] = 15'h7d8c;   // ff6666
    mem[235] = 15'h7d93;   // ff6699
    mem[236] = 15'h7d99;   // ff66cc
    mem[237] = 15'h7d9f;   // ff66ff
    mem[238] = 15'h7e60;   // ff9900
    mem[239] = 15'h7e66;   // ff9933
    mem[240] = 15'h7e6c;   // ff9966
    mem[241] = 15'h7e73;   // ff9999
    mem[242] = 15'h7e79;   // ff99cc
    mem[243] = 15'h7e7f;   // ff99ff
    mem[244] = 15'h7f20;   // ffcc00
    mem[245] = 15'h7f26;   // ffcc33
    mem[246] = 15'h7f2c;   // ffcc66
    mem[247] = 15'h7f33;   // ffcc99
    mem[248] = 15'h7f39;   // ffcccc
    mem[249] = 15'h7f3f;   // ffccff
    mem[250] = 15'h7fe0;   // ffff00
    mem[251] = 15'h7fe6;   // ffff33
    mem[252] = 15'h7fec;   // ffff66
    mem[253] = 15'h7ff3;   // ffff99
    mem[254] = 15'h7ff9;   // ffffcc
    mem[255] = 15'h7fff;   // ffffff
    mem[256] = 15'h0000;   // 000000
    mem[257] = 15'h001f;   // 0000ff
    mem[258] = 15'h03e0;   // 00ff00
    mem[259] = 15'h7c00;   // ff0000
    mem[260] = 15'h0000;   // 000000
    mem[261] = 15'h7fe0;   // ffff00
    mem[262] = 15'h7c1f;   // ff00ff
    mem[263] = 15'h7c00;   // ff0000
    mem[264] = 15'h0000;   // 000000
    mem[265] = 15'h03ff;   // 00ffff
    mem[266] = 15'h001f;   // 0000ff
    mem[267] = 15'h7c1f;   // ff00ff
    mem[268] = 15'h0000;   // 000000
    mem[269] = 15'h03e0;   // 00ff00
    mem[270] = 15'h03ff;   // 00ffff
    mem[271] = 15'h7fe0;   // ffff00
    mem[272] = 15'h0000;   // 000000
    mem[273] = 15'h7c1f;   // ff00ff
    mem[274] = 15'h03ff;   // 00ffff
    mem[275] = 15'h7fff;   // ffffff
    mem[276] = 15'h0000;   // 000000
    mem[277] = 15'h7fff;   // ffffff
    mem[278] = 15'h7fff;   // ffffff
    mem[279] = 15'h7fff;   // ffffff
    mem[280] = 15'h0000;   // 000000
    mem[281] = 15'h5c00;   // bf0000
    mem[282] = 15'h4c00;   // 9f0000
    mem[283] = 15'h7c00;   // ff0000
    mem[284] = 15'h0000;   // 000000
    mem[285] = 15'h5fe0;   // bfff00
    mem[286] = 15'h4fe0;   // 9fff00
    mem[287] = 15'h7fe0;   // ffff00
    mem[288] = 15'h0000;   // 000000
    mem[289] = 15'h5c1f;   // bf00ff
    mem[290] = 15'h4c1f;   // 9f00ff
    mem[291] = 15'h7c1f;   // ff00ff
    mem[292] = 15'h0000;   // 000000
    mem[293] = 15'h4fe0;   // 9fff00
    mem[294] = 15'h4c1f;   // 9f00ff
    mem[295] = 15'h4c00;   // 9f0000
    mem[296] = 15'h0000;   // 000000
    mem[297] = 15'h5fe0;   // b8ff00
    mem[298] = 15'h5c1f;   // bf00ff
    mem[299] = 15'h5c00;   // bf0000
    mem[300] = 15'h0000;   // 000000
    mem[301] = 15'h03ff;   // 00ffff
    mem[302] = 15'h7fe0;   // ffff00
    mem[303] = 15'h7c00;   // ff0000
    mem[304] = 15'h0000;   // 000000
    mem[305] = 15'h7c00;   // ff0000
    mem[306] = 15'h03e0;   // 00ff00
    mem[307] = 15'h03ff;   // 00ffff
    mem[308] = 15'h0000;   // 000000
    mem[309] = 15'h03ff;   // 00ffff
    mem[310] = 15'h7fe0;   // ffff00
    mem[311] = 15'h7fff;   // ffffff
    mem[312] = 15'h0000;   // 000000
    mem[313] = 15'h7fe0;   // ffff00
    mem[314] = 15'h03e0;   // 00ff00
    mem[315] = 15'h7fff;   // ffffff
    mem[316] = 15'h0000;   // 000000
    mem[317] = 15'h03ff;   // 00ffff
    mem[318] = 15'h03e0;   // 00ff00
    mem[319] = 15'h7fff;   // ffffff
    mem[320] = 15'h0000;   // 000000
    mem[321] = 15'h0015;   // 0000aa
    mem[322] = 15'h02a0;   // 00aa00
    mem[323] = 15'h02b5;   // 00aaaa
    mem[324] = 15'h5400;   // aa0000
    mem[325] = 15'h5415;   // aa00aa
    mem[326] = 15'h5540;   // aa5500
    mem[327] = 15'h56b5;   // aaaaaa
    mem[328] = 15'h294a;   // 555555
    mem[329] = 15'h001f;   // 0000ff
    mem[330] = 15'h03e0;   // 00ff00
    mem[331] = 15'h03ff;   // 00ffff
    mem[332] = 15'h7c00;   // ff0000
    mem[333] = 15'h7c1f;   // ff00ff
    mem[334] = 15'h7fe0;   // ffff00
    mem[335] = 15'h7fff;   // ffffff
    mem[336] = 15'h0010;   // 000080
    mem[337] = 15'h7fff;   // ffffff
end

// the reload (the controller's hotkey АР2+РУС, azvideo.v): one cell a
// clock through port A, ahead of the processor's write for those clocks
reg [8:0] rl_adr = 9'd0;
reg       rl_on  = 1'b0;
always @(posedge clk) begin
    if (reload) begin rl_on <= 1'b1; rl_adr <= 9'd256; end
    else if (rl_on) begin rl_adr <= rl_adr + 9'd1; if (rl_adr == 9'd337) rl_on <= 1'b0; end
end

always @(posedge clk) begin
    if (rl_on)     mem[rl_adr] <= def_pal(rl_adr);
    else if (a_we) mem[a_adr] <= a_din;
    else           a_dout <= mem[a_adr];
end

always @(posedge clk) b_dout <= mem[b_adr];

// the same table as a function, for azvideo.v's palette reset (the
// controller's hotkey АР2+РУС): cells 256-337, the legacy sets, the
// 16-colour set and the monochrome pair, back to their power-up values
function [14:0] def_pal;
    input [8:0] i;
    case (i)
        9'd256: def_pal = 15'h0000;
        9'd257: def_pal = 15'h001f;
        9'd258: def_pal = 15'h03e0;
        9'd259: def_pal = 15'h7c00;
        9'd260: def_pal = 15'h0000;
        9'd261: def_pal = 15'h7fe0;
        9'd262: def_pal = 15'h7c1f;
        9'd263: def_pal = 15'h7c00;
        9'd264: def_pal = 15'h0000;
        9'd265: def_pal = 15'h03ff;
        9'd266: def_pal = 15'h001f;
        9'd267: def_pal = 15'h7c1f;
        9'd268: def_pal = 15'h0000;
        9'd269: def_pal = 15'h03e0;
        9'd270: def_pal = 15'h03ff;
        9'd271: def_pal = 15'h7fe0;
        9'd272: def_pal = 15'h0000;
        9'd273: def_pal = 15'h7c1f;
        9'd274: def_pal = 15'h03ff;
        9'd275: def_pal = 15'h7fff;
        9'd276: def_pal = 15'h0000;
        9'd277: def_pal = 15'h7fff;
        9'd278: def_pal = 15'h7fff;
        9'd279: def_pal = 15'h7fff;
        9'd280: def_pal = 15'h0000;
        9'd281: def_pal = 15'h5c00;
        9'd282: def_pal = 15'h4c00;
        9'd283: def_pal = 15'h7c00;
        9'd284: def_pal = 15'h0000;
        9'd285: def_pal = 15'h5fe0;
        9'd286: def_pal = 15'h4fe0;
        9'd287: def_pal = 15'h7fe0;
        9'd288: def_pal = 15'h0000;
        9'd289: def_pal = 15'h5c1f;
        9'd290: def_pal = 15'h4c1f;
        9'd291: def_pal = 15'h7c1f;
        9'd292: def_pal = 15'h0000;
        9'd293: def_pal = 15'h4fe0;
        9'd294: def_pal = 15'h4c1f;
        9'd295: def_pal = 15'h4c00;
        9'd296: def_pal = 15'h0000;
        9'd297: def_pal = 15'h5fe0;
        9'd298: def_pal = 15'h5c1f;
        9'd299: def_pal = 15'h5c00;
        9'd300: def_pal = 15'h0000;
        9'd301: def_pal = 15'h03ff;
        9'd302: def_pal = 15'h7fe0;
        9'd303: def_pal = 15'h7c00;
        9'd304: def_pal = 15'h0000;
        9'd305: def_pal = 15'h7c00;
        9'd306: def_pal = 15'h03e0;
        9'd307: def_pal = 15'h03ff;
        9'd308: def_pal = 15'h0000;
        9'd309: def_pal = 15'h03ff;
        9'd310: def_pal = 15'h7fe0;
        9'd311: def_pal = 15'h7fff;
        9'd312: def_pal = 15'h0000;
        9'd313: def_pal = 15'h7fe0;
        9'd314: def_pal = 15'h03e0;
        9'd315: def_pal = 15'h7fff;
        9'd316: def_pal = 15'h0000;
        9'd317: def_pal = 15'h03ff;
        9'd318: def_pal = 15'h03e0;
        9'd319: def_pal = 15'h7fff;
        9'd320: def_pal = 15'h0000;
        9'd321: def_pal = 15'h0015;
        9'd322: def_pal = 15'h02a0;
        9'd323: def_pal = 15'h02b5;
        9'd324: def_pal = 15'h5400;
        9'd325: def_pal = 15'h5415;
        9'd326: def_pal = 15'h5540;
        9'd327: def_pal = 15'h56b5;
        9'd328: def_pal = 15'h294a;
        9'd329: def_pal = 15'h001f;
        9'd330: def_pal = 15'h03e0;
        9'd331: def_pal = 15'h03ff;
        9'd332: def_pal = 15'h7c00;
        9'd333: def_pal = 15'h7c1f;
        9'd334: def_pal = 15'h7fe0;
        9'd335: def_pal = 15'h7fff;
        9'd336: def_pal = 15'h0010;
        9'd337: def_pal = 15'h7fff;
        default: def_pal = 15'd0;
    endcase
endfunction

endmodule
